import pandas as pd
import streamlit as st
from sklearn.compose import ColumnTransformer
from sklearn.ensemble import GradientBoostingClassifier, RandomForestClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score
from sklearn.model_selection import train_test_split
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import OneHotEncoder, StandardScaler
from sklearn.tree import DecisionTreeClassifier
from sklearn.neighbors import KNeighborsClassifier


DATA_FILE = "loan.csv"
TARGET = "Loan Approved"


@st.cache_data
def load_data():
    return pd.read_csv(DATA_FILE)


@st.cache_resource
def train_models(data):
    features = data.drop(columns=[TARGET])
    target = data[TARGET].astype(int)
    categorical_columns = features.select_dtypes(include=["object", "str"]).columns.tolist()
    numeric_columns = features.select_dtypes(exclude=["object", "str"]).columns.tolist()

    preprocessor = ColumnTransformer(
        transformers=[
            ("categorical", OneHotEncoder(handle_unknown="ignore"), categorical_columns),
            ("numeric", StandardScaler(), numeric_columns),
        ]
    )

    x_train, x_test, y_train, y_test = train_test_split(
        features, target, test_size=0.2, random_state=42, stratify=target
    )
    model_definitions = {
        "Logistic Regression": LogisticRegression(max_iter=1000, random_state=42),
        "Decision Tree": DecisionTreeClassifier(max_depth=8, random_state=42),
        "Random Forest": RandomForestClassifier(
            n_estimators=150, max_depth=12, n_jobs=-1, random_state=42
        ),
        "Gradient Boosting": GradientBoostingClassifier(random_state=42),
        "K-Nearest Neighbors": KNeighborsClassifier(n_neighbors=9),
    }

    trained_models = {}
    scores = {}
    for name, classifier in model_definitions.items():
        pipeline = Pipeline(
            [("preprocessor", preprocessor), ("classifier", classifier)]
        )
        pipeline.fit(x_train, y_train)
        trained_models[name] = pipeline
        scores[name] = accuracy_score(y_test, pipeline.predict(x_test))

    best_model_name = max(scores, key=scores.get)
    return trained_models, scores, best_model_name, categorical_columns, numeric_columns


st.set_page_config(page_title="Loan Approval Predictor", page_icon=":bank:", layout="wide")
st.title("Loan Approval Predictor")
st.caption("Compare classification models and estimate approval for a new application.")

data = load_data()
models, scores, best_model_name, categorical_columns, numeric_columns = train_models(data)

st.subheader("Model accuracy")
score_table = pd.DataFrame(
    {"Model": list(scores.keys()), "Accuracy": [f"{score:.2%}" for score in scores.values()]}
).sort_values("Accuracy", ascending=False)
st.dataframe(score_table, hide_index=True, width="stretch")
st.caption("Scores use a stratified 80/20 holdout split with random state 42.")

st.subheader("Predict a loan application")
with st.form("loan_form"):
    input_values = {}
    columns = st.columns(3)
    for index, column in enumerate(categorical_columns):
        choices = sorted(data[column].dropna().unique().tolist())
        input_values[column] = columns[index % 3].selectbox(column, choices)
    for index, column in enumerate(numeric_columns):
        minimum = float(data[column].min())
        maximum = float(data[column].max())
        default = float(data[column].median())
        input_values[column] = columns[index % 3].number_input(
            column, min_value=minimum, max_value=maximum, value=default
        )
    submitted = st.form_submit_button("Predict approval")

if submitted:
    application = pd.DataFrame([input_values], columns=data.drop(columns=[TARGET]).columns)
    prediction = int(models[best_model_name].predict(application)[0])
    probability = float(models[best_model_name].predict_proba(application)[0][1])
    if prediction == 1:
        st.success(f"Loan approved (probability: {probability:.1%})")
    else:
        st.error(f"Loan not approved (approval probability: {probability:.1%})")
    st.caption(f"Prediction generated by the best validation model: {best_model_name}.")